### ISSUE TITLE
Should we use `SafeMath` from OpenZeppelin?

### ISSUE THREAD

**Issue by acuarica** [Ethernautas/renpool#86]
As mentioned in https://blog.openzeppelin.com/openzeppelin-contracts-4-0/

> _[...]_ Solidity 0.8 marks the end of the SafeMath era, as overflow checks are now built into the compiler.
> 
> You will find that SafeMath is still in the repository, athough it is now just a wrapper over the built-in overflow checks.

I see no point in use `SafeMath`. Am I missing something @fede-rodes?

**Comment by fede-rodes** [comment]
@acuarica agree, seems like there is no need for this library anymore

**Comment by acuarica** [comment]
We can remove `TODO` below then

https://github.com/Ethernautas/renpool/blob/74e18f0480af7dc633e612be3d0c501c304cc2ea/contracts/RenPool.sol#L9

**Comment by acuarica** [comment]
Migrated to new repo.
